LKLK/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from projectapp.views import ProjectListView

urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('joins/', include('joinapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, hello, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('hello/', hello, name='hello')
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView, ProjectUpdateView, ProjectDeleteView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', ProjectDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ProjectUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDeleteView.as_view(), name='delete'),
]

accountapp/models.py
from django.db import models

# Create your models here.

joinapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Join(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='join')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='join')

    #하나의 user가 프로젝트를 한번만 join할 수 있도록
    class Meta:
        unique_together = ('user', 'project')

projectapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Project(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)

    title = models.CharField(max_length=200, null=False)#제목이 꼭 있도록 null=False
    image = models.ImageField(upload_to='project/', null=False)
    image2 = models.ImageField(upload_to='project/', null=False)
    image3 = models.ImageField(upload_to='project/', null=False)

    content = models.TextField(null=False)#내용도 꼭 있도록 null=False

    created_at = models.DateField(auto_now_add=True, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from joinapp.models import Join
from projectapp.models import Project
from projectapp.views import ProjectDetailView

has_ownership = [account_ownership_required, login_required]

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    def get_context_data(self, **kwargs):
        object_list = Project.objects.filter(writer=self.get_object())
        join_list = Join.objects.all()
        return super(AccountDetailView, self).get_context_data(object_list=object_list,
                                                               join_list=join_list, **kwargs)


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:detail')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

def hello(request):
    return render(request, 'accountapp/hello.html')

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>

    </div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}


{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto">

            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt=""
                 style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
            <h2 style="font-family: 'NanumSquareB'">
                {{ target_user.profile.nickname }}

                {% if target_user == user %}
                <a class="material-icons"
                   style="box-shadow: 0 0 4px #ccc; border-radius:10rem; padding: .4rem"
                   href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                    edit
                </a>
                {% endif %}
            </h2>
             <h5 style="margin-bottom:3rem;">
                {{ target_user.profile.message }}
            </h5>
            {% else %}
                {% if target_user == user %}
                <a href="{% url 'profileapp:create' %}">
                    <h2 style="font-family: 'NanumSquareB'">
                        CreateProfile
                    </h2>
                </a>
                {% else %}
                <h2>
                    닉네임 미설정
                </h2>
                {% endif %}
            {% endif %}

            {% if target_user == user %}
            <a class="material-icons"
                style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
                href="{% url 'accountapp:update' pk=user.pk %}">
                settings
            </a>
            <a class="material-icons"
                style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;"
                href="{% url 'accountapp:delete' pk=user.pk %}">
                cancel
            </a>
            {% endif %}
 <hr>
        </div>

        <div style="text-align: center; margin: 4rem auto">
             <h2>
                 <!--  현재 내가 쓴 프로젝트만 보임 -->
                 My project
                {% include 'snippets/list_fragment.html' with project_list=object_list %}
             </h2>
        </div>

         <div style="text-align: center; margin: 4rem auto">
             <h2>
                  join

                 {% for join in join_list %}
                    {% if target_user == join.user %}
                        <a href="{% url 'projectapp:detail' pk=join.project.pk %}">
                            <div class="container" style="margin: 2rem auto">
                                <img src="{{ join.project.image.url }}" alt=""> <br>
                                {{ join.project.title }}
                            </div>
                        </a>
                    {% endif %}
                 {% endfor%}
<!--             {% include 'snippets/list_fragment.html' with project_list=join_list %}-->
             </h2>
        </div>

    </div>

{% endblock %}

accountapp/templates/accountapp/hello.html
{% extends 'base.html' %}


{% block content %}


    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        로그인 축하한다
    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}


    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>

         <hr>

        <div class="LKLK_login_navbar">

            <a href="{% url 'accountapp:create' %}" class="LKLK_login_nav">
                <span style="font-size: .9rem;">SignUp</span>
            </a>
            <a href="{% url 'accountapp:login' %}" class="LKLK_login_nav">
                <span style="font-size: .9rem;">ID 찾기</span>
            </a>
            <a href="{% url 'accountapp:login' %}" class="LKLK_login_nav">
                <span style="font-size: .9rem;">비밀번호 찾기</span>
            </a>

        </div>

    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>ChangeInfo</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}