LKLK/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from projectapp.views import ProjectListView

urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('joins/', include('joinapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, hello, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('hello/', hello, name='hello')
]

joinapp/urls.py
from django.urls import path

from joinapp.views import JoinView

app_name = "joinapp"

urlpatterns = [
    path('join/', JoinView.as_view(), name='join')
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView, ProjectUpdateView, ProjectDeleteView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', ProjectDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ProjectUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDeleteView.as_view(), name='delete'),
]

joinapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Join(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='join')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='join')

    #하나의 user가 프로젝트를 한번만 join할 수 있도록
    class Meta:
        unique_together = ('user', 'project')

projectapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Project(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='project', null=True)

    title = models.CharField(max_length=200, null=False)#제목이 꼭 있도록 null=False
    image = models.ImageField(upload_to='project/', null=False)
    image2 = models.ImageField(upload_to='project/', null=False)
    image3 = models.ImageField(upload_to='project/', null=False)

    content = models.TextField(null=False)#내용도 꼭 있도록 null=False

    created_at = models.DateField(auto_now_add=True, null=True)

projectapp/forms.py
from django.forms import ModelForm
from django import forms


from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'style': 'height: auto;'}))
    project = forms.ModelChoiceField(queryset=Project.objects.all(), required=False)

    class Meta:
        model = Project
        fields = ['title', 'image', 'image2', 'image3', 'project', 'content']

projectapp/views.py
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin

from joinapp.models import Join
from projectapp.decorators import project_ownership_required
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def form_valid(self, form):
        temp_project = form.save(commit=False)
        temp_project.writer = self.request.user
        temp_project.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user
        join_list = Join.objects.all()
        if user.is_authenticated:
            join = Join.objects.filter(user=user, project=project)
        else:
            join = None

        return super(ProjectDetailView, self).get_context_data(join_list=join_list, join=join, **kwargs)


@method_decorator(project_ownership_required, 'get')
@method_decorator(project_ownership_required, 'post')
class ProjectUpdateView(UpdateView):
    model = Project
    context_object_name = 'target_project'
    form_class = ProjectCreationForm
    template_name = 'projectapp/update.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(project_ownership_required, 'get')
@method_decorator(project_ownership_required, 'post')
class ProjectDeleteView(DeleteView):
    model = Project
    context_object_name = 'target_project'
    success_url = reverse_lazy('projectapp:list')
    template_name = 'projectapp/delete.html'


class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 25

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Project Create</h4>
    </div>
    <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

projectapp/templates/projectapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Delete Project : {{ target_project.title }}</h4>
    </div>
    <form action="{% url 'projectapp:delete' pk=target_project.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div>
    <div style="text-align:center; max-width:500px; margin: 4rem auto">

       <h1>
           {{target_project.title}}
       </h1>

        <a href="{% url 'accountapp:detail' pk=target_project.writer.pk %}" >
            <h4>
                <img src="{{ target_project.writer.profile.image.url }}" alt=""
                     style="height: 3rem; width: 3rem; border-radius: 10rem; object-fit: cover;">

                {{ target_project.writer.profile.nickname }}
            </h4>
        </a>

        <hr>
        <h5>
            {{target_project.content}}
        </h5>

        <img src="{{target_project.image.url}}" alt=""  class="container">
        <img src="{{target_project.image2.url}}" alt=""  class="container">
        <img src="{{target_project.image3.url}}" alt=""  class="container">

    <!--        구직 인원, 지원자 수 (-> 구현 전 프로젝트 생성시 지원자 수 추가생성 )-->

    <!--        프로젝트 글쓴이일 경우 수정, 삭제 권한, join 지원자 보기-->
        {% if target_project.writer == user %}
            <a href="{% url 'projectapp:update' pk=target_project.pk %}">
                <p>Update Project</p>
            </a>
            <a href="{% url 'projectapp:delete' pk=target_project.pk %}">
                <p>Delete Project</p>
            </a>
        <hr>
             <h4>Join List</h4>

            <!--        join 한 유저의 정보 받아오기       -->
            {% for join in join_list %} <!-- view.py의 projectDetail 에서 join 과 join_list 따로 받아왔음. -->
                {% if target_project.pk == join.project.pk %}
                <div style="margin: 2rem auto">
                    <a href="{% url 'accountapp:detail' pk=join.user.pk %}" >
                        <h4>
    <!--                    프로필 설정이 안되어있을 경우, 추후 기본이미지로 표시    -->
    <!--                    추후 count 변수 생성 후 지원자수 출력, 지원자 == 0일경우 문구 출력-->
                            {% if join.user.profile.image %}
                                <img src="{{ join.user.profile.image.url }}" alt=""
                                     style="height: 3rem; width: 3rem; border-radius: 10rem; object-fit: cover;">
                            {% endif %}

                            {{ join.user }}

<!--                            지원 수락 거절 만들기 -->

                        </h4>
                    </a>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}


    <!--        로그인 한 경우 join버튼 구현 완료, 추후 프로젝트 만든 사람의 오픈카톡링크 -->
        <div class="text-center mb-5">
            {% if user.is_authenticated and target_project.writer != user %}
                {% if not join %}
                <a href="{% url 'joinapp:join' %}?project_pk={{ target_project.pk }}"
                    class="btn btn-primary rounded-pill px-4">
                    join
                </a>
                {% else %}
                <a href="{% url 'joinapp:join' %}?project_pk={{ target_project.pk }}"
                    class="btn btn-dark rounded-pill px-4">
                    Unjoin
                </a>
                {% endif %}
            {% endif %}
        </div>

        <hr>
        <a href="{% url 'home' %}">
            <p>다른 프로젝트 보기</p>
        </a>
    </div>
</div>
{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


  <a href="{% url 'projectapp:create' %}" class="btn-hero w-button">
      <span>Post</span>
  </a>


  {% if project_list %}
    <div>
      {% for project in project_list %}
        {% include 'snippets/card.html' with project=project %}
      {% endfor %}
    </div>

  {% else %}
  <div >
    <h1>No Articles YET!</h1>
  </div>
  {% endif %}


{% endblock %}

projectapp/templates/projectapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Project Update</h4>
    </div>
    <form action="{% url 'projectapp:update' pk=target_project.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}