LKLK/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from projectapp.views import ProjectListView

urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('joins/', include('joinapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, hello, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('hello/', hello, name='hello')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko" data-wf-page="60f31dfb76fbf1c63ef328d2" data-wf-site="60e27ae019dce303dbf47fd0">

{% include 'head.html' %}

<body class="body">
{% include 'header.html' %}

    <div class="content-section wf-section">
        <div class="left-block"></div>
        <div class="main-block">
            <div class="w-container">
            {% block content %}
            {% endblock %}
            </div>
        </div>
        <div class="right-block"></div>
    </div>

  <div class="footer wf-section">
    <div class="button-wrap-2"></div>
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=60e27ae019dce303dbf47fd0" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="/static/js/webflow.js" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>

templates/footer.html
    <div style="text-align:center; margin-bottom: 2rem;">

        <div style="font-size: .9rem;">
            <span>하상우</span>
            <span>최지현</span>
            <span>김범창</span>
        </div>
        <div style="margin-top: 1rem;">
            <a href="https://udr.oopy.io/" >
                <h6>UNDERDOG</h6>
            </a>
        </div>

    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>LKLK_page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="Webflow" name="generator">
    <!-- webflow -->
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/webflow.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/lklk-myself-5db6ebca3a1b2c6738b8fab031e.webflow.css' %}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">WebFont.load({  google: {    families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic","Montserrat:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic"]  }});</script>
    <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->

    <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'images/webclip.png' %}" rel="apple-touch-icon">

</head>

templates/header.html
<header id="nav" class="nav-bar">
    <nav data-w-id="b2d25b6e-70cb-bec1-9a55-6e68f28386c1" style="opacity:0" class="container w-container">
        <ul role="list" class="nav-grid w-list-unstyled">
            <li id="w-node-b2d25b6e-70cb-bec1-9a55-6e68f28386c3-3ef328d2" class="list-item">
                <a href="{% url 'home' %}" class="link-block-3 w-inline-block">
                    <div class="logo-box">
                        <div class="logo_text k-2">L</div>
                        <div class="logo_text l-3">K</div>
                        <div class="logo_text k-4">L</div>
                        <div class="logo_text l-1">K</div>
                    </div>
                </a>
            </li>

            <li >
                {% if not user.is_authenticated %}
                    <a href="{% url 'accountapp:login' %}?next={{ request.path }}" target="_blank" class="btn-hero w-button">
                        <span>Login</span>
                    </a>
                {% else %}
                    <li>
                    </li>

                    <li>
                        <div data-hover="" data-delay="0" class="w-dropdown">
                            <div class="dropdown-toggle w-dropdown-toggle"><img src="/static/images/human.png" loading="lazy" width="50" height="50" alt="" class="profilebtn"></div>
                            <nav class="dropdown-list w-dropdown-list">
                                <a  href="{% url 'accountapp:detail' pk=user.pk %}" class="dropdownbtn mypagebtn w-button">Mypage</a>
                                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="dropdownbtn logoutbtn w-button">Logout</a>
                            </nav>
                        </div>
                    </li>
                {% endif %}
            </li>
        </ul>
    </nav>
</header>